// cmd/api/main.go
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"sukumad/internal/migrate"
	"sukumad/internal/seeder"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	log "github.com/sirupsen/logrus"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"sukumad/config"
	apphttp "sukumad/internal/http"
	"sukumad/internal/middleware"

	// swagger docs are generated by: swag init -g ./cmd/api/main.go -o ./internal/docs
	_ "sukumad/internal/docs"
)

// @title           Sukumad API
// @version         1.0
// @description     CRUD for servers, requests, and deliveries with rate-limited worker.
// @BasePath        /
// @schemes         http https
func main() {
	cfg := config.AppConfig

	// ----- Logging
	if cfg.Debug {
		log.SetLevel(log.DebugLevel)
	}
	// Use JSON logs by default; switch with SUKUMAD_LOG_FORMAT=text if you prefer
	log.SetFormatter(&log.JSONFormatter{TimestampFormat: time.RFC3339Nano})

	// ----- Gin mode
	if cfg.Debug {
		gin.SetMode(gin.DebugMode)
	} else {
		gin.SetMode(gin.ReleaseMode)
	}

	// ----- Register custom validators used by binding tags
	apphttp.RegisterCustomValidators()

	// ----- DB connect (context will be cancelled on shutdown)
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	pool, err := pgxpool.New(ctx, cfg.DBURL)
	if err != nil {
		log.WithError(err).Fatal("pgxpool connect failed")
	}
	defer pool.Close()

	sqlDB, err := migrate.RunWithPostgresDriver(ctx, cfg.DBURL)
	if err != nil {
		log.WithError(err).Fatal("migrations failed")
	}
	defer sqlDB.Close()

	if cfg.SeedSampleData {
		if err := migrate.LoadFixturesWithPostgresDriver(ctx, sqlDB); err != nil {
			log.WithError(err).Fatal("fixtures failed")
		}
	}

	if err := seeder.Run(ctx, pool, seeder.Options{
		AdditionalPermCodes: []string{
			"can_view_deliveries",
			"can_expand_requests",
			"can_view_requests",
		},
	}); err != nil {
		log.WithError(err).Fatal("permission seeder failed")
	}

	// ----- Router + middleware
	r := gin.New()
	r.Use(gin.Recovery(), middleware.RequestLogger(), middleware.CORSFromConfig(cfg))

	// Register app routes
	rt := apphttp.NewRouter(pool, cfg)
	rt.Register(r)

	log.Info("Registered API Endpoints:")
	for _, route := range r.Routes() {
		log.Infof(" %-6s  %-40s  %s", route.Method, route.Path, route.Handler)
	}

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ----- HTTP server
	addr := fmt.Sprintf(":%d", func() int {
		if cfg.Port > 0 {
			return cfg.Port
		}
		return 8383
	}())
	srv := &http.Server{
		Addr:              addr,
		Handler:           r,
		ReadTimeout:       15 * time.Second,
		ReadHeaderTimeout: 10 * time.Second,
		WriteTimeout:      60 * time.Second,
		IdleTimeout:       120 * time.Second,
	}

	// Run server in background
	go func() {
		log.WithField("listen", addr).Info("http server starting")
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.WithError(err).Fatal("http server crashed")
		}
	}()

	// ----- Wait for shutdown signal
	<-ctx.Done()
	log.Info("shutdown signal received; draining HTTP server...")

	// Create shutdown context (grace period)
	shCtx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()

	// Stop new requests, allow in-flight to finish
	if err := srv.Shutdown(shCtx); err != nil {
		log.WithError(err).Error("graceful shutdown failed; forcing close")
		if cerr := srv.Close(); cerr != nil {
			log.WithError(cerr).Error("server close failed")
		}
	} else {
		log.Info("http server shut down gracefully")
	}

	// Pool close happens in defer; give it a moment to release
	time.Sleep(100 * time.Millisecond)
	log.Info("bye 👋")
}
